#!/bin/bash
echo --- device-register ----
cd /code/device-register
echo Getting go modules....
# go get ./...
echo Building device-register ....
# go build ./...

echo --- test-server ----
cd /server
echo Getting go modules....
go get ./...
echo Building testing-server....
go build ./...
echo Running test server...
./testing-server