#!/bin/bash
echo --- device-register ----
cd /code/device-register
echo Building device-register ....
go build ./...

echo --- test-server ----
cd /server
echo Building testing-server....
go build ./...
echo Running test server...
./testing-server